language: ruby

rvm:
  - 2.5.8

jdk: openjdk8

before_install:
  - gem update --system 2.7.10
  - gem --version

cache:
  - bundler

script:
  - bundle exec rake test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bundle exec rake publish; fi

notifications:
  slack:
    secure: "K85xR9b1VQMK2c3KpXjho4WBz1fTIUSfsmLCMFRkYY8ykOoH7fjBLRJRQtAOMfjUNfjDt+VMwFTky0F8lMmZRMnBBYZ8mTzhmKjJY0ToWLiDIJm48ncPleJRzMR0ku9xU7x1DHB6QEMu6DFXkgoe4/b0VOsFwYzQGmelfZNhD6U="
