language: ruby

before_install:
- rvm implode --force
- \curl -sSL https://get.rvm.io | bash -s 1.29.7
- rvm reload
- gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.3 bundler -x
- gem install bundler -v 1.17.3

rvm:
  - 2.5.3

jdk: openjdk8

cache:
  - bundler

script:
  - bundle exec rake test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bundle exec rake publish; fi

notifications:
  slack:
    secure: "K85xR9b1VQMK2c3KpXjho4WBz1fTIUSfsmLCMFRkYY8ykOoH7fjBLRJRQtAOMfjUNfjDt+VMwFTky0F8lMmZRMnBBYZ8mTzhmKjJY0ToWLiDIJm48ncPleJRzMR0ku9xU7x1DHB6QEMu6DFXkgoe4/b0VOsFwYzQGmelfZNhD6U="
